### ISSUE TITLE
How to individually configure reporters output?

### ISSUE THREAD

**Issue by sinedied** [mattlewis92/karma-coverage-istanbul-reporter#1]
I just migrated from `karma-remap-istanbul-reporter`, and in the configuration I could configure output for istanbul reporters like this:
```
      reports: {
        html: 'reports/coverage',
        lcovonly: './reports/coverage/coverage.lcov',
        'text-summary': ''
      },
```
while it seems that I can only specify which reporters to use in your tool:
```
      reports: ['html', 'lcovonly', 'text-summary'],
```

Is there a way to configure reporters output?

**Comment by mattlewis92** [comment]
Sorry the documentation on this is pretty lacking, I will go through and sort it at some point. As this is just a very thin wrapper across the [istanbul-reports](https://github.com/istanbuljs/istanbul-reports) lib, any config that can be passed to that lib is valid. Unfortunately the docs for that don't exist either 😞 

This is extracted from reading the source for each of the [reports here](https://github.com/istanbuljs/istanbul-reports/tree/master/lib), it should match the config you were using with `karma-remap-istanbul`
```
coverageIstanbulReporter: {
  reports: ['html', 'lcovonly', 'text-summary'],
  dir: './reports/coverage', // base output directory
  'report-config': {
    html: { // any options here are valid: https://github.com/istanbuljs/istanbul-reports/blob/master/lib/html/index.js#L134-L139
   },
   lcovonly: {
     // options from here are valid: https://github.com/istanbuljs/istanbul-reports/blob/master/lib/lcovonly/index.js#L7-L10
     file: 'coverage.lcov'
   }
  },
  fixWebpackSourcePaths: true
}
```

Hope that helps! 😄

**Comment by sinedied** [comment]
Thanks, that was exactly was I was looking for!

**Comment by abobwhite** [comment]
@mattlewis92 Thanks - I just pulled this up because a similar option, `karma-remap-coverage` was blowing up trying to write the cobertura report whereas yours does not. 

A problem I'm seeing is that the `subdir` option of the html reporter is not being honored. It seems no matter what I do, the html reports go to the `coverage` folder as a sibling to my `src` folder (which is actually one level up from my karma config. Furthermore, even when I don't list `html` in my reports list, it STILL does this. Any chance there is an issue with this?

```
coverageIstanbulReporter: {
      reports: ['text-summary', 'html', 'cobertura'],

      // base output directory
      dir: REPORTS_PATH,

      // if using webpack and pre-loaders, work around webpack breaking the source path
      fixWebpackSourcePaths: true,

      // Most reporters accept additional config options. You can pass these through the `report-config` option
      'report-config': {
        html: {
          subdir: 'html'
        },
        cobertura: {
          file: 'coverage.xml'
        },
        'text-summary': {
          file: null
        }
      }
    }
```

**Comment by abobwhite** [comment]
It's worth noting that the `file` property for the cobertura reporter is working just fine

**Comment by mattlewis92** [comment]
What's the value of the reports_path variable? Would you be able to share a repo that demonstrates your problem that I can clone and hack about with to see if I can find a solution?

**Comment by abobwhite** [comment]
Thanks @mattlewis92 

```REPORTS_PATH = `${__dirname}/../../build/jasmine-reports` ```

My project structure:
+ project/
++ build/
+++ jasmine-reports/ (WHERE I EXPECT the html folder)
++ api/
++ ui/
+++ src/
+++ test/
++++karma.conf.js

This variable worked fine for other reporters such as `karma-remap-coverage` I mentioned above

**Comment by abobwhite** [comment]
If nothing pops out for you, I can make a sample repo for you.

**Comment by abobwhite** [comment]
UPDATE: What I mentioned above is what happens without adding 'html' to `reports`. If I DO add it, then it's worse. It tries to do it but then it blows up with the following error:

`ERROR [karma]: Error: Cannot write to absolute path: C:/Git/project/ui/src/app/index.html`

**Comment by mattlewis92** [comment]
I can't see anything obviously wrong with that, if you can give me a minimal sample repo I can try and debug more. I suspect it's probably an issue with the underlying Istanbul API and windows compatibility , rather than this lib specifically which is a very tiny integration between Istanbul and karma.

**Comment by abobwhite** [comment]
Thanks, @mattlewis92 that's what I'm suspecting too. I bet it's the good ole `/` vs `\` issue. If I can't figure it out, i'll create a new issue with a minimal example repo for you

**Comment by mattlewis92** [comment]
Awesome, thanks 👍🏻
