### ISSUE TITLE
exclude files from coverage report

### ISSUE THREAD

**Issue by joshdanhall** [mattlewis92/karma-coverage-istanbul-reporter#14]
I cannot figure out how to exclude files from the coverage report.

**Comment by mattlewis92** [comment]
Just don't instrument them with the Istanbul-instrumenter-loader and they won't be included in the report.

**Comment by mattlewis92** [comment]
There is a good example of how the angular cli implemented it here: https://github.com/angular/angular-cli/commit/b6893d0

**Comment by joshdanhall** [comment]
Thanks @mattlewis92 , the reference to angular-cli is exactly what I needed!
