### ISSUE TITLE
class arrow functions resulting in unexpected token

### ISSUE THREAD

**Issue by danehansen** [mattlewis92/karma-coverage-istanbul-reporter#17]
i recently switched over to `karma-coverage-istanbul-reporter` on a couple projects and the ones where i am exporting a class as the default, are breaking when i test. i narrowed it down to the presence of fat arrow functions. if i remove them everything works fine. it seems that maybe `stage-0` is not being turned on somehow? any ideas to point me to how to fix this? karma.conf.js is as follows:

`const webpack = require('webpack');

module.exports = function (config) {
  config.set({
    browsers: ['Chrome'],
    frameworks: ['mocha', 'chai', 'sinon'],
    singleRun: false,
    reporters: ['coverage-istanbul'],
    files: [
      {'pattern': 'test/math.test.js', 'watched': true,  'included': true,  'served': true},
      {'pattern': 'test/fake.test.js', 'watched': true,  'included': true,  'served': true},
      {'pattern': 'test/fake-class.test.js', 'watched': true,  'included': true,  'served': true},
    ],
    preprocessors: {
      'test/**/*.js': ['webpack', 'sourcemap'],
    },
    webpack: {
      module: {
        rules: [{
          test: /\.js$/,
          exclude: [/node_modules/],
          loader: 'istanbul-instrumenter-loader',
          enforce: 'post',
          options: {
            presets: ['es2015', 'stage-0'],
            esModules: true,
          },
        }],
      },
      plugins: [
        new webpack.SourceMapDevToolPlugin({
          filename: null,
          test: /\.js($|\?)/i
        }),
      ],
      resolve: {
        extensions: ['.js'],
      },
    },
    webpackMiddleware: {
      stats: 'errors-only',
      noInfo: true,
    },
    coverageIstanbulReporter: {
      reports: ['html'],
      dir: 'coverage',
    },
  })
}
`

**Comment by mattlewis92** [comment]
From what you posted it looks like you're using babel? In which case if you swap the istanbul-instrumenter-loader for this [babel plugin](https://github.com/istanbuljs/babel-plugin-istanbul) it should work.
