### ISSUE TITLE
--include-all-sources option for Coverage in Karma.conf

### ISSUE THREAD

**Issue by PieterLeRoux** [mattlewis92/karma-coverage-istanbul-reporter#18]
Is there a way to make use of --include-all-sources option of Istanbul? Currently all files with 0% coverage are skipped.

**Comment by mattlewis92** [comment]
This module only reports on what was instrumented by the babel plugin / istanbul instrumenter loader. As long as the source files are included somewhere in your bundle via require / import they should appear in the coverage report.

**Comment by mkay581** [comment]
I know this was closed but I'm also running into this issue. The documentation says that this package allows us to pass arguments to the istanbul api using the `instrumentation` property. Why wouldn't something like this work with the config?

```js
{
      // `instrumentation` is used to configure Istanbul API package.
      instrumentation: {
        'include-all-sources': true
      }
}
```
