### ISSUE TITLE
Global/File Thresholds - Warning Configuration

### ISSUE THREAD

**Issue by curtiszjohn** [mattlewis92/karma-coverage-istanbul-reporter#19]
First off, great reporter, in addition to the latest enhancements that were implemented.  Wondering if we can expand on an existing enhancement...

Enhancement request: can we have a configuration that throws a warning instead of a hard fail when the coverage doesn't meet the threshold? See an example configuration below: 

thresholds: {
	**alert: "warning", // options: "fail", "warning"**
	global: { // thresholds for all files
		statements: 100,
		lines: 100,
		branches: 100,
		functions: 100
	},
	each: { // thresholds per file
		statements: 100,
		lines: 100,
		branches: 100,
		functions: 100
	}
}

We've implemented pre-commit hook that checks the threshold but would prefer it throws a warning rather than preventing the commit.  Thoughts?

**Comment by mattlewis92** [comment]
Makes sense, I've added this in 1.3.0 🎉
