### ISSUE TITLE
Overriding configuration for thresholds based on filnname pattern

### ISSUE THREAD

**Issue by mahmood-sajjadi** [mattlewis92/karma-coverage-istanbul-reporter#20]
Do we have any option like:
https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check

I am using [karma-coverage-istanbul-reporter] for angular4 project, and I need different coverage thresholds for *.component.ts and *.service.ts and base classes

**Comment by mattlewis92** [comment]
Added in 1.3.0 😄
