### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by megamindbrian** [mattlewis92/karma-coverage-istanbul-reporter#21]
Do I need to direct any files: {} to this?

**Comment by mattlewis92** [comment]
It simply reports on whatever was instrumented via either the webpack instrumenter or the babel plugin. If you're not using either of these then you probably just want to stick with regular old karma-coverage.

**Comment by megamindbrian** [comment]
No one ever told me a need an instanbul-instrument-loader in my webpack.
Now I have to figure out where that came from.

**Comment by mattlewis92** [comment]
It does say right in the first section of the readme: https://github.com/mattlewis92/karma-coverage-istanbul-reporter#about

You can see a full e2e example of how to combine them here: https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/test/karma.conf.js

**Comment by megamindbrian** [comment]
Maybe it's just me but with all the npm noise out there I would put
frameworks that it applies to front and center. Do you think people
generally treat their GitHub pages with SEO considerations?

On Jun 12, 2017 12:00 PM, "Matt Lewis" <notifications@github.com> wrote:

It does say right in the first section of the readme: https://github.com/
mattlewis92/karma-coverage-istanbul-reporter#about

You can see a full e2e example of how to combine them here:
https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/
test/karma.conf.js

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattlewis92/karma-coverage-istanbul-reporter/issues/21#issuecomment-307886184>,
or mute the thread

**Comment by megamindbrian** [comment]
Good advice. What I want is when I Google search for "angular code
coverage" everything to just popup and work on its own. But I'm stuck
following Alice down the rabbit hole at every turn.
