### ISSUE TITLE
Suppress coverage warnings if not all tests are run

### ISSUE THREAD

**Issue by tuhoojabotti** [mattlewis92/karma-coverage-istanbul-reporter#22]
Sometimes I'm working on a single file/module and I use `fdescribe` to only run those tests. The problem is that then I get coverage errors from 100+ files.

I'm not sure if it is possible with a reporter, but there could be an option that if fdescribe or skipped tests are detected, the the reporter would not log individual coverage errors (maybe just global stats to remind you that coverage is broken) and still exit with non-zero exit code in case fdescribe somehow gets to CI.

Any ideas?

**Comment by mattlewis92** [comment]
As the tests are run in the browser, karma (which is run in node), would have no way of knowing if focused tests were used, so you'd have to set up some sort of message bus between the browser and karma, that monkey patches fdescribe to determine if it was used (which is a far from clean solution and way outside the scope of this module). For your use case though I can see a fairly straight forward path, which is to the use the emitWarning option in this reporter, and set it to true if not on CI (any good CI service should set appropriate environment variables to determine this). Then you can use a lint rule to enforce no fdescribe in tests: https://github.com/tlvince/eslint-plugin-jasmine/blob/HEAD/docs/rules/no-focused-tests.md

**Comment by tuhoojabotti** [comment]
Yes I see the problem. Unfortunately emitWarning does not solve the problem, because I run tests in watch mode anyway. The problem is the amount of log messages that forces me to scroll a lot in the console to see the failing tests.

A quick workaround is to only setup global coverage thresholds, which isn't as nice, but works quite well in our case since we force 100 % coverage anyway, we just have to ignore branch coverage because it's not reported correctly right now with Angular components and services using DI.

And for linting it's a great idea and I actually already implemented it using TSlint's ban-rule.

**Comment by mattlewis92** [comment]
Ah I see your problem, I don't think is any solution that would work well for your use case as there is so many dynamic factors at play. I wouldn't really recommend instrumenting test coverage during local test runs in watch mode anyway, as it massively slows down build times and is better enforced by a CI run. 

This is a bit of a personal opinion as well, but I always find enforcing test coverage forces you to write contrived tests that don't reflect live scenarios, just to hit the coverage mark. By having 100% test coverage it also falsely gives a sense that the code is well tested, when in fact you can have a bunch of bad tests that don't really test the code properly and still results in regressions.
