### ISSUE TITLE
Exclude file from coverage report

### ISSUE THREAD

**Issue by TheCodeDestroyer** [mattlewis92/karma-coverage-istanbul-reporter#23]
Is there a way to exclude some files from the report without affecting the tests?

Something like:
```
remapOptions: {
  exclude: 'PATH'
}
```

**Comment by mattlewis92** [comment]
As this lib only reports on whatever was instrumented, you would need to not instrument those sources to exclude them from being reported on. Assuming you were using webpack with the istanbul instrumenter loader, you can exclude files via webpacks config:
```
test: /src\/.+\.ts$/,
exclude: [
  /node_modules/,
  /\.spec\.ts$/,
  /path\/to\/some\/file/.ts/
],
loader: 'istanbul-instrumenter-loader',
enforce: 'post'
```

**Comment by TheCodeDestroyer** [comment]
Actually I have an embedded webpack inside angular cli, so I only have access to karma config file.

**Comment by mattlewis92** [comment]
Ah ok, in which case the CLI has baked in support for this: https://github.com/angular/angular-cli/pull/4966

**Comment by TheCodeDestroyer** [comment]
Thanks so much didn't know about that!
