### ISSUE TITLE
Showing errors in the HTML report

### ISSUE THREAD

**Issue by jrmcdona** [mattlewis92/karma-coverage-istanbul-reporter#25]
Hello,
When view the HTML output file.  I only see green for coverage even though I have tests failing.
Am I reading it wrong or do I have a config wrong?

I would expect the HTML would be showing some red for the test failure.   Can you let me know how I can include what fails in the output.

Thanks

**Comment by mattlewis92** [comment]
Code coverage only indicates which lines of code were executed, it doesn't actually indicate which tests failed and which passed. As long as every line in a file is ran by your tests it will be included as green in the report.
