### ISSUE TITLE
How to exclude files from coverage report

### ISSUE THREAD

**Issue by kentonbmax** [mattlewis92/karma-coverage-istanbul-reporter#26]
I have a test framework with common service mocks that I want to exclude from the coverage report. I believe there was a way to do this with the remap reporter. Can you please add an example of this to the readme?

Also another situation would be an angular app that has 2 main areas supported by 2 different teams. File separation by module would be a nice to have.

**Comment by mattlewis92** [comment]
This reporter only reports what code was instrumented. You can use the CLI to exclude files from the coverage report: https://github.com/angular/angular-cli/pull/4966

File separation by module is outside the scope of this library, its just a tiny wrapper over [istanbul](https://github.com/istanbuljs/istanbuljs) that does all the actual code instrumentation + report generation.
