### ISSUE TITLE
Not getting any output?

### ISSUE THREAD

**Issue by mattgrande** [mattlewis92/karma-coverage-istanbul-reporter#29]
Hi there. I'm trying to switch from `karma-coverage` to your plugin, but I'm getting no output when running my tests.

I assume I'm missing something obvious in my `karma.conf.js` file? Any thoughts?

```
const path = require('path');

module.exports = function( config ) {

    var configuration = {

        basePath : '../',

        autoWatch : true,

        frameworks: ['jasmine'],

        browsers : ['ChromeHeadless'],

        plugins : [
            'karma-coverage-istanbul-reporter',
            'karma-jasmine',
            'karma-chrome-launcher',
            'karma-mocha-reporter'
        ],

        reporters: ['mocha', 'coverage-istanbul'],
        coverageIstanbulReporter: {
            reports: ['text', 'html'],
            dir: path.join(__dirname, '..', 'coverage')
        },

        mochaReporter : {
          output: 'minimal'
        },

        client: {
            captureConsole: false
        },

        customLaunchers: {
            Chrome_travis_ci: {
                base: 'Chrome',
                flags: ['--headless', '--disable-gpu', '--remote-debugging-port=9222']
            }
        }
    };

    if (process.env.TRAVIS) {
        configuration.browsers = ['Chrome_travis_ci'];
    }

    config.set(configuration);
};
```

There's no output at all (ie, it's as if the coverage configs aren't there), and the `coverage` directory doesn't get created.

**Comment by mattlewis92** [comment]
You need to use either [babel or webpack](https://github.com/mattlewis92/karma-coverage-istanbul-reporter#about) to instrument your code first, otherwise the reporter won't pick up on the changes. If you're not transpiling your code then there's no reason to use this reporter and you can stick with karma-coverage. Hope that helps! 😄

**Comment by mattgrande** [comment]
That makes a tonne of sense. Thanks!
