### ISSUE TITLE
Highlighting files

### ISSUE THREAD

**Issue by abyrne85** [mattlewis92/karma-coverage-istanbul-reporter#31]
Coverage works fine but highlighting un-covered parts of the typscript files is broken
![image](https://user-images.githubusercontent.com/3189515/33673871-df972400-daa5-11e7-89bc-a22fe976ff52.png)

**Comment by mattlewis92** [comment]
It sounds like an issue with your sourcemaps. This library is only a tiny wrapper over istanbul, you'd be better off opening an issue there with a minimal repo that reproduces your issue: https://github.com/istanbuljs/istanbuljs
