### ISSUE TITLE
Combined coverage

### ISSUE THREAD

**Issue by bryanforbes** [mattlewis92/karma-coverage-istanbul-reporter#34]
I'm attempting to get coverage for multiple browsers (in my case, 10 browsers launched with `karma-browserstack-launcher`) in one report. Right now, the only two options I see are:

1. Only get the report from the last browser session (without using `%browser%`, the plugin writes the reports to the same place multiple times)
2. Get multiple reports organized by browser name (using `%browser%`)

**Comment by mattlewis92** [comment]
Unfortunately the only option you have is to use `%browser%` and output to multiple directories - istanbul AFAIK doesn't have any API for merging multiple runs together. This is how the original `karma-coverage` worked as well. Sorry I couldn't be of more help 😞

**Comment by bryanforbes** [comment]
> istanbul AFAIK doesn't have any API for merging multiple runs together

`CoverageMap#addFileCoverage()` [merges coverage info](https://github.com/istanbuljs/istanbuljs/blob/45936de1356b743dcf82df729bf3da895e180aea/packages/istanbul-lib-coverage/lib/coverage-map.js#L110) when data exists internally for a file. Would you accept a PR to add a configuration flag to merge the data from all runs?

**Comment by mattlewis92** [comment]
Ah, I didn't know about that, yeah would be happy to accept a PR to add this functionality then 😄

**Comment by bryanforbes** [comment]
I'll work something up and do a pull request within the next few days. I rewrote the loop for a project I'm working on so that it combines the information, I'll just need to abstract the similar parts out and make the flag switch between how the collection is done.
