### ISSUE TITLE
Cannot read property 'combineBrowserReports' of undefined

### ISSUE THREAD

**Issue by it11ah1** [mattlewis92/karma-coverage-istanbul-reporter#36]
config.coverageIstanbulReporter.combineBrowserReports leads to "TypeError: Cannot read property 'combineBrowserReports' of undefined" if coverageIstanbulReporter is not set in karma.conf.js.
Perhaps a solution as seen in createReport(browserOrBrowsers, results) may help?

**Comment by mattlewis92** [comment]
Sorry about that, should be fixed now in 1.4.1 😄
