### ISSUE TITLE
Add a flag which can stop output messages from test failed

### ISSUE THREAD

**Issue by Aqours** [mattlewis92/karma-coverage-istanbul-reporter#37]
![image](https://user-images.githubusercontent.com/8586286/35560825-7df5ca20-05e9-11e8-9192-26e0d3a0e1b5.png)

The above failed message, 1 from karma-coverage-istanbul-reporter and 2 from karma-mocha-reporter.
I only need mocha-reporter message in shell/cmd. But I also need karma-coverage-istanbul-reporter to generate coverage information except failed message in shell/cmd. So could you add a flag which can stop output messages from test failed?

**Comment by mattlewis92** [comment]
Ah, the issue is with karma, AFAIK there is no workaround I can implement here until karma opens up an API that would allow me to fix this. For more info see this issue: https://github.com/karma-runner/karma/issues/2342 Sorry that I couldn't be of more help! 😞
