### ISSUE TITLE
LCOV report contains wrong information

### ISSUE THREAD

**Issue by josefarinna** [mattlewis92/karma-coverage-istanbul-reporter#40]
Hello,

Using SonarQube I realized that the generated lcov report has incorrect data. SonarQube output when analizes the lcov is something like this:
`WARN: Problem during processing LCOV report: can't save DA data for line 139 of coverage report file (java.lang.IllegalArgumentException: Line with number 154 doesn't belong to file src/app/app.component.ts).
WARN: Problem during processing LCOV report: can't save DA data for line 140 of coverage report file (java.lang.IllegalArgumentException: Line with number 156 doesn't belong to file src/app/app.component.ts).
WARN: Problem during processing LCOV report: can't save DA data for line 263 of coverage report file (java.lang.IllegalArgumentException: Line with number 197 doesn't belong to file src/app/_common/case-converter.ts).
WARN: Problem during processing LCOV report: can't save DA data for line 264 of coverage report file (java.lang.IllegalArgumentException: Line with number 199 doesn't belong to file src/app/_common/case-converter.ts).
`

After analizing the file by myself I could check that SonarQube is right, because the lcov contains lines that doesnt exist in my source files. So the coverage that SonarQube is reporting doesnt have any sense

I'm using the lates version (1.4.2) of the reporter.

**Comment by mattlewis92** [comment]
This reporter only reports on the data given to it by the instrumentation step so there isn't anything actionable here, it sounds like it might be related to this issue: https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/73
