### ISSUE TITLE
How to disable private methods from coverage?

### ISSUE THREAD

**Issue by thigrand** [mattlewis92/karma-coverage-istanbul-reporter#41]
Hey guys, 
Client demands high coverage, but there is no sense to tests private methods. 
Is there any way to not track coverage for private methods?

**Comment by mattlewis92** [comment]
As this reporter is only a thin wrapper around istanbul you should be able to use comments to ignore certain features: https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md
