### ISSUE TITLE
Ignore some files to cover

### ISSUE THREAD

**Issue by SimBrunet** [mattlewis92/karma-coverage-istanbul-reporter#42]
Hi, 
I am developping an app for a project at school, and I use istanbul reporter to get tests reports. the thing is I want to cover only some files of the code that is made (the parts I am coding only) since we are a team of dev on the projects. 
Is there a way to exclude a path in the karma.conf.js or anywhere else ? 
Thank you.

**Comment by mattlewis92** [comment]
Hi there, as this only reports on the files that were instrumented, you can get this functionality by not running those files through whatever you're using to instrument them. e.g. for webpack, you would exclude those files here: https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/test/karma.conf.js#L18-L25 and then only the source files that are ran through the `istanbul-instrumenter-loader` will appear in the coverage report. Hope that helps! 😄
