### ISSUE TITLE
Line numbers for Branch coverage seems not to be correct

### ISSUE THREAD

**Issue by deeptowncitizen** [mattlewis92/karma-coverage-istanbul-reporter#45]
I have angular-cli starter project.
I added few new components with some specs, and configured karma istanbul to report in Cobertura format.

The problem is that in the outcome report I have some not covered branches which point to lines with `import`, empty lines. It looks like non-relevant.

How to map not covered lines to typescript source files properly?

**Comment by mattlewis92** [comment]
This package only reports on code that was instrumented before, I think the bug is with the webpack loader that does the instrumentation of the code: https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/73
