### ISSUE TITLE
[Refused to apply inline style because it violates the following Content Security Policy] Publishing coverage report in Jenkins, got errors in console and few styles are not applied. 

### ISSUE THREAD

**Issue by krishlakshmanan** [mattlewis92/karma-coverage-istanbul-reporter#46]
After code coverage generation, published this reports as an HTML report in the Jenkins. We couldn't see the progressed chart styles in the report, observed these console errors as follows. 

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-lHXTXVoMUY2/p3pxQI6CRA0n02Rrs2+ZoQFL/rrqCXA='), or a nonce ('nonce-...') is required to enable inline execution.

Same error is not reproduced in my local machine, issue comes only as part of Jenkins Html Report.

**Comment by mattlewis92** [comment]
This is only a small wrapper around istanbul, you would be better off raising an issue there with a minimal repro: https://github.com/istanbuljs/istanbuljs
