### ISSUE TITLE
Wrong path style on windows

### ISSUE THREAD

**Issue by Viatorus** [mattlewis92/karma-coverage-istanbul-reporter#47]
I am not quite sure why on Windows the path separator backslash gets replaced with a slash:

https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/c484c1ae49ad1a4d0fc3b83314f8e4fbd781c822/src/util.js#L14-L19

This leads to two issues for me:
* the HTML pages of `nyrc report` land in the wrong directory
* the coverage report of `nyrc jasmine` and `karma` can not be merged because of different paths (Unix and Windows style)

On linux, this issue does not exist.

---

I have to use `fixWebpackSourcePaths: true` because of using webpack and typescript.

Disabling `fixWebpackSourcePaths` and removing the source paths by hand solves the issue.

---

Please check it out at Windows: 
https://github.com/LokiJS-Forge/LokiDB

Running `npm run test:web` creates under _coverage/karma_ the coverage in JSON notation containing the Unix path style.

Running `npm run test:node` creates under _coverage/node_ the coverage in JSON notation containing the Windows path style (does not use karma of course).

Running `npm run coverage` puts the HTML pages into the _coverage_ and _packages_ folder because of the Unix path style.

**Comment by mattlewis92** [comment]
Hey, so sorry about the late reply on this one, been a manic few months here changing jobs and country. I've just cut `2.0.3` with a fix for this, please let me know if that works ok for you 😄
