### ISSUE TITLE
Wrong coverage report

### ISSUE THREAD

**Issue by Ratikant01** [mattlewis92/karma-coverage-istanbul-reporter#48]
Is it correct coverage report? I am not sure what exactly it is pointing? any help? Using "karma-coverage-istanbul-reporter": "^1.2.1",

![image](https://user-images.githubusercontent.com/5038421/42879110-1fc6be98-8aad-11e8-8da2-f9dafaf7adaf.png)

**Comment by mattlewis92** [comment]
That normally happens when your sourcemaps are incorrect, this module only reports on what was instrumented by the webpack loader / babel, you need to raise an issue with whatever tool you're using to instrument the code.
