### ISSUE TITLE
Low coverage with latest angular cli

### ISSUE THREAD

**Issue by adappter** [mattlewis92/karma-coverage-istanbul-reporter#51]
Hey there,

the coverage of my tests are getting low when using the latest angular/cli

```
    "@angular-devkit/build-angular": "0.7.2",
    "@angular-devkit/core": "0.7.2",
    "@angular/cli": "6.1.2",
    "jasmine-core": "3.1.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.5",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-istanbul-threshold": "1.2.2",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "1.2.0",
    "karma-mocha-reporter": "2.2.5",
```
The `@angular-devkit/build-angular": "0.7.2"` dependency seems to be the problem. If I downgrade to 0.6.8 the coverage threshold is correct.

I don't know if this issue is correct here.
Thanks for help!

**Comment by mattlewis92** [comment]
Looks like an issue with the angular cli itself, I don't think there's anything I can do this end to fix it: https://github.com/angular/angular-cli/issues/11672
