### ISSUE TITLE
Update istanbul-api to v2.x

### ISSUE THREAD

**Issue by Sibiraj-S** [mattlewis92/karma-coverage-istanbul-reporter#52]
Update `istanbul-api`, which has a dependency of `istanbul-lib-hook` While installation, it produces a deprecated warning

`npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump`

**Comment by mattlewis92** [comment]
It's already on the [latest version](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/package.json#L41): https://www.npmjs.com/package/istanbul-api

**Comment by Sibiraj-S** [comment]
@mattlewis92 . The latest version is v2.0.5. I don't know the reason why those are published with next tag. Can you keep this issue open until it is figured?

**Comment by Sibiraj-S** [comment]
The latest version is published with `next` tag for regression testing https://github.com/istanbuljs/istanbuljs/issues/209

**Comment by mattlewis92** [comment]
Sure, will leave open until 2.x is marked as stable and then update it (sidenote: I don't see this warning from npm when installing this module, maybe try cleaning your npm cache and re-installing your node_modules)

**Comment by Sibiraj-S** [comment]
Only occurs when installing with  no `package-lock.json` i.e., a fresh installation

![screen shot 2018-08-10 at 9 25 05 pm](https://user-images.githubusercontent.com/20282546/43968148-e99ed2ee-9ce3-11e8-91a7-09e95c4ea797.png)

**Comment by mattlewis92** [comment]
Looks like istanbul 2.x is stable now, I've just cut `2.0.3` with the upgrade, hope that works for you! 😄

**Comment by Sibiraj-S** [comment]
Cool 👍
