### ISSUE TITLE
Changing "skipFilesWithNoCoverage" to false still results in file missing from LCOV report if using source maps

### ISSUE THREAD

**Issue by lqc** [mattlewis92/karma-coverage-istanbul-reporter#53]
Due to https://github.com/istanbuljs/istanbuljs/issues/214, remapping the coverage map erases the file from the report.

As a workaround, such files count be re-added to the map after sourceMap transformation is applied.

**Comment by mattlewis92** [comment]
If you could send a PR with a fix that would be great! 😄
