### ISSUE TITLE
Coverage Differs from Actual In Angular Tree Components

### ISSUE THREAD

**Issue by J8299** [mattlewis92/karma-coverage-istanbul-reporter#57]
I can go through every line of this in Karma for PhantomJS & Chrome. Debug either & get ~98% of lines "hit" but the coverage does not reflect that & reflects different numbers for Phantom & Chrome.

Reusing the check function logic:
https://angular2-tree.readme.io/v4.0.0/docs/tri-state-checkboxes

I tried Mobx to observe the changing TreeNode & "fixture when stable." It seems not to register changes in the TreeNode map, which changes the path, using either the Observed or original TreeNode object. The code goes through all relate lines of code when debugged & the observable TreeNode shows correct values.

PhantomJS:
![image](https://user-images.githubusercontent.com/30184441/46362699-0097fc80-c63f-11e8-8082-cd2f8eb48c84.png)

Chrome:
![image](https://user-images.githubusercontent.com/30184441/46362772-2f15d780-c63f-11e8-8c35-47a3a856dbbf.png)

Dependencies:
Karma 3.0.0
karma-coverage-istanbul-reporter 3.0.0
karma-phantomjs-launcher 1.0.4
karma-coverage-istanbul-reporter 2.0.4
node v8.9.4
npm 6.4.0
Angular CLI: 1.6.7
Angular: 5.2.11

**Comment by mattlewis92** [comment]
This lib is only a tiny wrapper over the [istanbul](https://github.com/istanbuljs/istanbuljs) api and only reports on what it was given by other tooling. I would recommend raising an issue over on the angular cli or istanbul repos with a minimal failing repro that demonstrates your problem.
