### ISSUE TITLE
Coverage Report json-summary produces invalid json

### ISSUE THREAD

**Issue by whyao** [mattlewis92/karma-coverage-istanbul-reporter#6]
Hey,

When using angular-cli to generate a json summary of the code coverage, the json that is generated is invalid. This was done on a windows computer and I've debugged this issue and found that the backslashes need to be escaped. See the screenshots for more info.

![image](https://cloud.githubusercontent.com/assets/4923736/23192831/71b786c4-f85a-11e6-8b33-cd9ce9777bd8.png)

![image](https://cloud.githubusercontent.com/assets/4923736/23192845/83c7f3ee-f85a-11e6-8bef-515333acbf76.png)

**Comment by mattlewis92** [comment]
This is an issue with Istanbul itself, I've sent them a PR to fix it, more info here: https://github.com/mattlewis92/karma-coverage-istanbul-reporter/issues/5
