### ISSUE TITLE
Document include-all-sources

### ISSUE THREAD

**Issue by levibotelho** [mattlewis92/karma-coverage-istanbul-reporter#7]
I'm struggling a bit to figure out how to get the reporter to include data for untested files. Istanbul supports this with the [`include-all-sources` option](https://github.com/istanbuljs/istanbul-api/blob/47b7803fbf7ca2fb4e4a15f3813a8884891ba272/lib/config.js#L28).

Is there an easy way to do this with the reporter as-is, or does this require some development work? I'd be happy to contribute if needed.

EDIT: Just realized that this might be the job of the instrumenter and not the reporter. If that's the case then I'll take this up with the istanbul instrumenter loader crowd :).

**Comment by mattlewis92** [comment]
You're correct, this reporter just reports on anything that has been instrumented by the instrumenter loader. All you need to do is make sure all of your webpack sources are imported / required somewhere in your webpack bundle and then included via the instrumenter loader config [like this](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/test/karma.conf.js#L16). Hope that helps! 😄
