### ISSUE TITLE
Files are not being output

### ISSUE THREAD

**Issue by talltyler** [mattlewis92/karma-coverage-istanbul-reporter#8]
I'm having trouble getting files to be output. Any report that outputs to the console works fine, anything that needs to write a file isn't outputting anything. I assume this has something to do with my use of webpack and a conflict with the istanbul-instrumenter maybe, but if I take this out the text and other console based reports also stop working. Here is my current config.

    module.exports = function (config) {
      config.set({

        singleRun: true,

        frameworks: ['mocha'],

        files: [
          'test/**/*_test.js'
        ],

        preprocessors: {
          'test/**/*_test.js': [ 'webpack' ]
        },

        reporters: ['spec', 'coverage-istanbul'],

        coverageIstanbulReporter: {

          reports: ['text', 'html'],

          dir: './coverage',

          fixWebpackSourcePaths: true

        },

        webpack: {
          module: {
            loaders: [
              {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/
              }
            ],
            postLoaders: [{
              test: /\.js/,
              exclude: /(test|node_modules)/,
              loader: 'istanbul-instrumenter'
            }]
          }
        },

        webpackMiddleware: {
          noInfo: true
        },

        browsers: ['Chrome']
      })
    }

The output I get has no errors and looks like this

    ...
    Chrome 56.0.2924 (Mac OS X 10.12.3): Executed 17 of 17 SUCCESS (0.153 secs / 0.07 secs)
    TOTAL: 17 SUCCESS

    09 03 2017 10:26:35.644:DEBUG [reporter.coverage-istanbul]: Writing coverage reports: [ 'html', 'text' ]
    --------------------|----------|----------|----------|----------|----------------|
    File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
    --------------------|----------|----------|----------|----------|----------------|
    All files           |       60 |    35.71 |       25 |    48.39 |                |
     lib                |       60 |    35.71 |       25 |    48.39 |                |
      external.js       |       60 |    35.71 |       25 |    48.39 |... 93,94,95,96 |
    --------------------|----------|----------|----------|----------|----------------|
    09 03 2017 10:26:35.823:DEBUG [karma]: Run complete, exiting.
    09 03 2017 10:26:35.824:DEBUG [launcher]: Disconnecting all browsers
    09 03 2017 10:26:35.837:DEBUG [launcher]: Process Chrome exited with code 0
    09 03 2017 10:26:35.838:DEBUG [temp-dir]: Cleaning temp dir /var/folders/_l/qm339dw95kng31rypmqfl7240000gp/T/karma-78185743
    09 03 2017 10:26:35.871:DEBUG [launcher]: Finished all browsers
    >

**Comment by mattlewis92** [comment]
Can you share a repo that reproduces your problem? I can't see anything obviously wrong with your config. Possibly it's because the file hasn't been written before karma exits, if you run karma in watch mode does anything get outputted then? Perhaps try setting `dir: path.join(__dirname, 'coverage')`

**Comment by talltyler** [comment]
Good call, `dir: path.join(__dirname, 'coverage')` fixed the issue. Thanks for looking at it so fast.

**Comment by mattlewis92** [comment]
NP, glad you got it sorted I've updated the readme with that fix which should hopefully help others in the future 😄  

btw I noticed you were using babel, you can get much more accurate coverage reporting by using the [babel plugin](https://github.com/istanbuljs/babel-plugin-istanbul) rather than the webpack instrumenter loader 😃

**Comment by talltyler** [comment]
Thanks I'll check it out.
