### ISSUE TITLE
emitWarning no longer work since version 3

### ISSUE THREAD

**Issue by alan-agius4** [mattlewis92/karma-coverage-istanbul-reporter#80]
Setting `emitWarning` to false no longer has an effect since version 3. The root cause seems to be that `onRunComplete` has been changed to an `async` function, but Karma is unable to handle this and `onRunComplete` needs to be a standard callback function.

To to repro, update the spec file to the below;
```ts
/* eslint-disable max-nested-callbacks */
const fs = require('fs');
const path = require('path');
const chai = require('chai');
const karma = require('karma');
const rimraf = require('rimraf');
const karmaCoverageIstanbulReporter = require('../src/reporter');
const { OUTPUT_LOG_FILE } = require('./karma.conf');

const { expect } = chai;
const OUTPUT_PATH = path.join(__dirname, 'fixtures', 'outputs');
const OUTPUT_FILE = path.join(OUTPUT_PATH, 'coverage-summary.json');
const OUTPUT_DETAILS_FILE = path.join(OUTPUT_PATH, 'coverage-final.json');
const fileReadTimeout = 300;

function createServer(config, cb) {
  config = config || {};
  config = cb || (() => { });
  return new karma.Server(
    Object.assign(
      {
        configFile: path.join(__dirname, '/karma.conf.js'),
        plugins: [
          'karma-mocha',
          'karma-phantomjs-launcher',
          'karma-webpack',
          'karma-sourcemap-loader',
          karmaCoverageIstanbulReporter,
        ],
      },
      config
    ),
    cb
  );
}

describe('karma-coverage-istanbul-reporter', () => {
  beforeEach(() => {
    rimraf.sync(OUTPUT_PATH);
    rimraf.sync(OUTPUT_LOG_FILE);
    fs.mkdirSync(OUTPUT_PATH);
  });
  it('should have an exitCode of non zero when emitWarning is false', (done) => {
    const server = createServer({
        coverageIstanbulReporter: {
          reports: ['json-summary'],
          dir: path.join(__dirname, 'fixtures', 'outputs'),
          fixWebpackSourcePaths: true,
          thresholds: {
            emitWarning: false,
            global: {
              statements: 50,
              lines: 50,
              branches: 50,
              functions: 50,
            },
            each: {
              statements: 80,
              lines: 80,
              branches: 80,
              functions: 60,
            },
          },
        },
      },
      exitCode => {
        expect(exitCode).to.equal(1);
        done();
      }
    );
    server.start();

  });
});

```

**Comment by mattlewis92** [comment]
Thanks for digging into this, would you mind making a PR with the test case + fix (just removing the async function should be enough I think?)

**Comment by alan-agius4** [comment]
@mattlewis92, not quite because the transform coverage API is async https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/b6632e22355cbcf8b45c1cb44d4795834e506f35/src/reporter.js#L105

**Comment by mattlewis92** [comment]
Ah yeah you're right, I had a quick look through the karma source and I can't see any way of making an async reporter, it always relies on it being done synchronously. I think I found a workaround though, the reporter used to do this to change the exit code: https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/v0.3.1/src/reporter.js#L69-L74 

IIRC the only reason I changed it was because I found the "proper" api in karma, but there was nothing really wrong with doing it that way.

**Comment by alan-agius4** [comment]
Well, that is a bit problematic if using Karma as an API, because the Karma run itself will be "successful" and only when the process exits will return an error.

**Comment by mattlewis92** [comment]
That's a really good point 😢 I had a quick look at the [angular cli](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/karma/index.ts#L158) and it doesn't look like you're using the exitCode from the api, so I think it should at least fix it for your use case. I'll release a patch version now with it, while it's not perfect, it's at least better than being completely broken.

**Comment by alan-agius4** [comment]
Actually the API is what we use https://github.com/angular/angular-cli/blob/d008cf2b83f206f6223b68b014aba5098e8992c2/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma.ts#L270

Forcefully using `process.exit` will break our repos testing setup.

I guess for now we’ll stick with version 2.

**Comment by mattlewis92** [comment]
Ah right, ok I'm going to put the dist tag on the npm package back to v2 until a proper solution can be found

**Comment by alan-agius4** [comment]
Thanks mate!

**Comment by mattlewis92** [comment]
@alan-agius4 you should be OK to upgrade to v3 of this lib now, @sebastianhaeni found a solution 😄

**Comment by alan-agius4** [comment]
Nice thanks
